"""
Discord Integration Module
Posts structured research report embeds and attaches generated PDF reports directly
to configured Discord channels via Discord Bot REST API using multipart/form-data.
Accepts and returns Python dictionaries.
"""

import json
import urllib.request
import uuid
from typing import Any

def send_report_to_discord(
    bot_token: str,
    channel_id: str,
    applicant_name: str,
    applicant_email: str,
    report: dict[str, Any],
    pdf_bytes: bytes
) -> dict[str, Any]:
    """
    Constructs and sends a multipart/form-data payload with Discord Embed and PDF Attachment.
    Returns Python dictionary with success status and message ID or error details.
    """
    bot_token = bot_token.strip()
    channel_id = channel_id.strip()
    
    if not bot_token or not channel_id:
        return {
            "success": False,
            "error": "Discord Bot Token and Channel ID are required."
        }
        
    url = f"https://discord.com/api/v10/channels/{channel_id}/messages"
    
    company_name = report.get("company_name", "Company Research Report")
    website = report.get("website", "")
    filename = f"{company_name.lower().replace(' ', '_')}_research_report.pdf"
    
    locs = report.get("locations", {})
    country = locs.get("country", "Global")
    cities_str = ", ".join([c.get("city_name", "") for c in locs.get("cities", [])])
    
    summary_pts = report.get("summary") or report.get("pain_points", [])
    first_summary = summary_pts[0] if summary_pts else "Research summary complete."

    payload_json = {
        "content": f"📊 **New Company Research Report Generated!**",
        "embeds": [{
            "title": f"🏢 {company_name} - Executive Corporate Summary",
            "description": f"Detailed AI research report generated by **Relu Consultancy Assistant**.",
            "url": website if website.startswith("http") else f"https://{website}",
            "color": 16103217, # Gold (#F5B731)
            "fields": [
                {
                    "name": "👤 Applicant Details",
                    "value": f"**Name:** {applicant_name or 'N/A'}\n**Email:** {applicant_email or 'N/A'}",
                    "inline": True
                },
                {
                    "name": "🌐 Location & Offices",
                    "value": f"**Country:** {country}\n**Cities:** {cities_str or 'HQ'}",
                    "inline": True
                },
                {
                    "name": "📦 Executive Summary",
                    "value": first_summary[:350],
                    "inline": False
                }
            ],
            "footer": {
                "text": "Relu Consultancy · AI & Automation Developer Hackathon"
            }
        }],
        "attachments": [{
            "id": 0,
            "description": f"PDF Research Report for {company_name}",
            "filename": filename
        }]
    }
    
    boundary = f"----WebKitFormBoundary{uuid.uuid4().hex}"
    body = bytearray()
    
    body.extend(f"--{boundary}\r\n".encode("utf-8"))
    body.extend(b'Content-Disposition: form-data; name="payload_json"\r\n')
    body.extend(b'Content-Type: application/json\r\n\r\n')
    body.extend(json.dumps(payload_json).encode("utf-8"))
    body.extend(b'\r\n')
    
    body.extend(f"--{boundary}\r\n".encode("utf-8"))
    body.extend(f'Content-Disposition: form-data; name="files[0]"; filename="{filename}"\r\n'.encode("utf-8"))
    body.extend(b'Content-Type: application/pdf\r\n\r\n')
    body.extend(pdf_bytes)
    body.extend(b'\r\n')
    
    body.extend(f"--{boundary}--\r\n".encode("utf-8"))
    
    headers = {
        "Authorization": f"Bot {bot_token}",
        "Content-Type": f"multipart/form-data; boundary={boundary}",
        "User-Agent": "DiscordBot (ReluConsultancy, 1.0)"
    }
    
    try:
        req = urllib.request.Request(url, data=bytes(body), headers=headers, method="POST")
        with urllib.request.urlopen(req, timeout=15) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            return {
                "success": True,
                "message_id": res_data.get("id"),
                "channel_id": channel_id,
                "status": "Message and PDF report sent to Discord successfully!"
            }
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8", errors="ignore")
        return {
            "success": False,
            "error": f"Discord API Error ({e.code}): {error_body[:200]}"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }
